name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: golang:1.13-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
